"use client";

import {
  Clock,
  Brain,
  Sparkles,
  BarChart3,
  Music,
  Sun,
  Keyboard,
  ChefHat,
  FolderOpen,
  Grid2x2,
  Mic,
  Trophy,
  Target,
  RefreshCw,
  Zap,
  Coffee,
  Flame,
  Plus,
  List,
  Bird,
  ClipboardList,
  Puzzle,
  Calendar,
  ArrowUp,
  TrendingUp,
  Settings,
  Volume2,
  Globe,
  Star,
  Palette,
  FolderKanban,
  Inbox,
  Rocket,
  CheckSquare,
  Compass,
  Search,
  CheckCircle,
  Eye,
  EyeOff,
  GripVertical,
  PenLine,
  MailOpen,
  Scale,
  Flower2,
  Lightbulb,
  MapPin,
  Pause,
  AlertTriangle,
  PartyPopper,
  Pin,
  Moon,
  Check,
  Hourglass,
  Download,
  Activity,
  Droplet,
  Wind,
  Footprints,
  type LucideProps,
} from "lucide-react";
import type { ComponentType } from "react";

const ICON_MAP: Record<string, ComponentType<LucideProps>> = {
  clock: Clock,
  brain: Brain,
  sparkles: Sparkles,
  "bar-chart": BarChart3,
  music: Music,
  sun: Sun,
  keyboard: Keyboard,
  "chef-hat": ChefHat,
  "folder-open": FolderOpen,
  grid: Grid2x2,
  mic: Mic,
  trophy: Trophy,
  target: Target,
  "refresh-cw": RefreshCw,
  zap: Zap,
  coffee: Coffee,
  flame: Flame,
  plus: Plus,
  list: List,
  bird: Bird,
  "clipboard-list": ClipboardList,
  puzzle: Puzzle,
  calendar: Calendar,
  "arrow-up": ArrowUp,
  "trending-up": TrendingUp,
  settings: Settings,
  volume: Volume2,
  globe: Globe,
  star: Star,
  palette: Palette,
  "folder-kanban": FolderKanban,
  inbox: Inbox,
  rocket: Rocket,
  "check-square": CheckSquare,
  compass: Compass,
  search: Search,
  "check-circle": CheckCircle,
  eye: Eye,
  "eye-off": EyeOff,
  "grip-vertical": GripVertical,
  "pen-line": PenLine,
  "mail-open": MailOpen,
  scale: Scale,
  flower: Flower2,
  lightbulb: Lightbulb,
  "map-pin": MapPin,
  pause: Pause,
  "alert-triangle": AlertTriangle,
  "party-popper": PartyPopper,
  pin: Pin,
  moon: Moon,
  check: Check,
  hourglass: Hourglass,
  download: Download,
  activity: Activity,
  droplet: Droplet,
  wind: Wind,
  footprints: Footprints,
};

interface LucideIconProps extends Omit<LucideProps, "ref"> {
  name: string;
}

/**
 * Renders a Lucide icon by string name.
 * Allows data structures (featureRegistry, commands, etc.) to reference icons as strings.
 */
export default function LucideIcon({ name, size = 16, ...props }: LucideIconProps) {
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return <Icon size={size} {...props} />;
}

export { ICON_MAP };
